const IMAGES = {
  GRADIENT: require('../assets/images/background_gold_gradient.png'),
  DENDA_LOGO: require('../assets/images/dendagrey.png'),
  DENDA_WHITE_LOGO: require('../assets/images/denda_white.png'),
  RECIPE01: require('../assets/images/recipe01.jpeg'),
  RECIPE02: require('../assets/images/recipe02.jpeg'),
  DENDA_TAB_BOTTOM_ICON: require('../assets/images/denda_tab_bottom_icon.png'),
  DENDA_TAB_BOTTOM_ICON_FOCUSED: require('../assets/images/denda_tab_bottom_icon_focused.png'),
  BLUE_PLAY: require('../assets/images/play_blue.png'),
  BLUE_PAUSE: require('../assets/images/pause_blue.png'),
  YELLOW_PLAY: require('../assets/images/play_yellow.png'),
  YELLOW_PAUSE: require('../assets/images/pause_yellow.png'),
  GREEN_PLAY: require('../assets/images/play_green.png'),
  GREEN_PAUSE: require('../assets/images/pause_green.png'),
  USER: require('../assets/images/user.jpg'),
  VERIFICATION01: require('../assets/images/01verification.png'),
  VERIFICATION02: require('../assets/images/02verification.png'),
  VERIFICATION03: require('../assets/images/03verification.png'),
  VERIFICATION04: require('../assets/images/04verification.png'),
  VERIFICATION_DIS_01: require('../assets/images/01verification_disable.png'),
  VERIFICATION_DIS_02: require('../assets/images/02verification_disable.png'),
  VERIFICATION_DIS_03: require('../assets/images/03verification_disable.png'),
  VERIFICATION_DIS_04: require('../assets/images/04verification_disable.png'),
  ACCOUNT: require('../assets/icons/account.png'),
  LOADING: require('../assets/icons/loading.png'),
  ROCKET: require('../assets/images/rocket.png'),
  WAITING: require('../assets/icons/waiting.png')
};

export default IMAGES;
